export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_COUNTPRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_COUNTPRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_COUNTPRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCTSBYPAGE_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTSBYPAGE_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTSBYPAGE_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCTS_BYTYPE_REQUEST = "GET_PRODUCTS_BYTYPE_REQUEST";
export const GET_PRODUCTS_BYTYPE_SUCCESS = "GET_PRODUCTS_BYTYPE_SUCCESS";
export const GET_PRODUCTS_BYTYPE_FAIL = "GET_PRODUCTS_BYTYPE_FAIL";

export const GET_PRODUCTS_BYTITLE_REQUEST = "GET_PRODUCTS_BYTITLE_REQUEST";
export const GET_PRODUCTS_BYTITLE_SUCCESS = "GET_PRODUCTS_BYTITLE_SUCCESS";
export const GET_PRODUCTS_BYTITLE_FAIL = "GET_PRODUCTS_BYTITLE_FAIL";

export const CREATE_PRODUCTS_REQUEST = "CREATE_PRODUCTS_REQUEST";
export const CREATE_PRODUCTS_SUCCESS = "CREATE_PRODUCTS_SUCCESS";
export const CREATE_PRODUCTS_FAIL = "CREATE_PRODUCTS_FAIL";

export const DEL_PRODUCTS_REQUEST = "DEL_PRODUCTS_REQUEST";
export const DEL_PRODUCTS_SUCCESS = "DEL_PRODUCTS_SUCCESS";
export const DEL_PRODUCTS_FAIL = "DEL_PRODUCTS_FAIL";

export const UPDATE_PRODUCTS_REQUEST = "UPDATE_PRODUCTS_REQUEST";
export const UPDATE_PRODUCTS_SUCCESS = "UPDATE_PRODUCTS_SUCCESS";
export const UPDATE_PRODUCTS_FAIL = "UPDATE_PRODUCTS_FAIL";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET";


